# Generated by Django 3.2.9 on 2021-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.IntegerField(max_length=200)),
                ('cEmail', models.IntegerField(max_length=150)),
                ('cSubject', models.IntegerField(max_length=100)),
                ('cMessage', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'CONTACT',
            },
        ),
    ]
